### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [bossly/photo-sharing-android#1]
Hello...

You have a FANTASTIC project... I came across your amazing project and I want to help use my Logo Design Skills to contribute to your project by creating a NEW LOGO/ICON that is clean and fully represent your project...

I am already working on an idea concept...

I will update the finished idea concept here so you can give me your feedback or possibly any change you may want...  if you have any specific colour in mind, you can also let me know...

Regards.

**Comment by bossly** [comment]
Hey! Thanks for the help :)

**Comment by chimzycash** [comment]
I'm glad for your reply... I will get the idea Design ready and update it here for your feedback

**Comment by chimzycash** [comment]
Hello @bossly 

Here is my idea concept...

![logo design_photosharing_background_icon](https://user-images.githubusercontent.com/37814297/41503543-08923e88-71cf-11e8-8008-519f1f9107a7.jpg)


![logo design_photosharing_presentation 2](https://user-images.githubusercontent.com/37814297/41503545-0d753cd4-71cf-11e8-9811-5320c8b747a9.jpg)


You can also share your own idea concept for me to create... also you can tell me the colour of your choice... :)

**Comment by bossly** [comment]
Hey, the icon is pretty cool, but really hard to find the logic behind. Maybe use something more simple? for example remove the sharing icon (lines and dot) and but the rectangle inside, and fill it.

**Comment by chimzycash** [comment]
Hello @bossly 
![logo design_coinguide_idea concept](https://user-images.githubusercontent.com/37814297/41616799-cfe0e75e-73f6-11e8-910a-bc12101fa5da.jpg)

**Comment by chimzycash** [comment]
Do you mean this?

![logo design_coinguide_idea concept 2](https://user-images.githubusercontent.com/37814297/41616893-0e16e7b2-73f7-11e8-87c4-bcea41e89d14.jpg)

**Comment by chimzycash** [comment]
You can sketch out a concept for easier clarification...

**Comment by bossly** [comment]
you can try to test your icon: http://www.appsparky.com

Personally like this one 
![resources-ios10-app-icon-template](https://user-images.githubusercontent.com/130861/41619429-83af3d58-7406-11e8-8576-9daca58058e1.jpg)

**Comment by chimzycash** [comment]
@bossly ... you want a logo with a similar concept as the icon on the image?

**Comment by chimzycash** [comment]
http://www.appsparky.com/?id=tJzkeU

**Comment by chimzycash** [comment]
you can do a brief sketch of the idea you have in mind, so as to make me understand better and we can discuss the idea

**Comment by bossly** [comment]
I am ready bad designer )will try to draw some, but I like that on I show you

**Comment by chimzycash** [comment]
OK... @bossly ... I will come up with another idea concept and update it here

**Comment by chimzycash** [comment]
![logo design_photosharing_background_icon 2](https://user-images.githubusercontent.com/37814297/41629400-3d5f099e-7421-11e8-99fe-0bad7b52c143.jpg)


http://www.appsparky.com/?id=fqivOS

http://www.appsparky.com/?id=MPabCw

You can check the two links

**Comment by bossly** [comment]
wow, looks really awesome :) we can definitely using it. Can you replace the icon in a project or want me to do that (if you can export icon for me than)?

**Comment by chimzycash** [comment]
Thanks @bossly ... 

The final files should look like this...:)

![logo design_photosharing_presentation 3](https://user-images.githubusercontent.com/37814297/41656751-fb378d9e-7488-11e8-9ac3-927268982bc6.jpg)


I am glad you liked the design... I will prepare the files with the vector files and Png and create a PULL REQUEST... 

i will also send you google drive link FOR YOUR USE any time too :)

you can also send me your email so we can communicate if you need any other files...

**Comment by bossly** [comment]
thanks for supporting open source 👍

**Comment by chimzycash** [comment]
hello @bossly i uploaded the files and created a pull request...

**Comment by chimzycash** [comment]
i will also upload in google drive and send you the link to the vector files

**Comment by bossly** [comment]
Can you please share the icons (maybe zip file), because the Pull Request is not correct.

**Comment by chimzycash** [comment]
@bossly ... OK sorry about that...

**Comment by chimzycash** [comment]
Here are the Google Drive Files...

Zipped file: https://drive.google.com/file/d/1zQvy3lN2_SH4_vSEIa8xsugl10vHZD6K/view?usp=sharing

No Zip: https://drive.google.com/drive/folders/1S-o36wG3TSNGxNxU_p7STWSJCf2qBkF-?usp=sharing

I'm really glad you liked my design and want to use it on your project... I always LOVE using my skills to contribute to Amazing OPEN SOURCE projects... :)

More success to your projects... Regards

**Comment by bossly** [comment]
Thanks! :) will keep in mind ;)

**Comment by chimzycash** [comment]
@bossly 
To help you out... is it possible for me to create another pull request and replace the files?

**Comment by chimzycash** [comment]
Hi @bossly ... It is possible to make the icon replacement myself in the res/drawable section?

**Comment by bossly** [comment]
> Hi @bossly ... It is possible to make the icon replacement myself in the res/drawable section?

yes, you can change it yourself and make PullRequest.
